### ISSUE TITLE
6

### ISSUE THREAD

**Issue by SnowUnderwater** [zhiziqixingdeng/zhizi#1]
https://github.com/zhiziqixingdeng/zhizi/blob/main/cpp%E6%96%87%E4%BB%B6/NOLstd%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F.cpp

6

代码全挤main函数

> while(1==1){

仓库根目录：“许可证”

不多说了lol

**Comment by zhiziqixingdeng** [comment]
这些代码由SLtyz委托我进行上传（因为他没有github），我也没看，我去看看这是什么

**Comment by zhiziqixingdeng** [comment]
> 这些代码由SLtyz委托我进行上传（因为他没有github），我也没看，我去看看这是什么

怎么SLtyz还放了用我的名义的代码

**Comment by zhiziqixingdeng** [comment]
我tm还以为质量多高的代码呢，SLtyz你给我出来

**Comment by zhiziqixingdeng** [comment]
> 我tm还以为质量多高的代码呢，SLtyz你给我出来

居然还把有些我自己私聊给他的东西直接复制粘贴了？

**Comment by zhiziqixingdeng** [comment]
> https://githubfast.com/zhiziqixingdeng/zhizi/blob/main/cpp%E6%96%87%E4%BB%B6/NOLstd%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F.cpp
> 
> 6
> 
> 代码全挤main函数
> 
> > 而（1==1）{
> 
> 仓库根目录："许可证"
> 
> 不多说了哈哈

代码全挤main函数好像是可读性的问题，while（1==1）好像跟while（true）没啥区别

**Comment by SnowUnderwater** [comment]
> > https://githubfast.com/zhiziqixingdeng/zhizi/blob/main/cpp%E6%96%87%E4%BB%B6/NOLstd%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F.cpp
> > 6
> > 代码全挤main函数
> > > 而（1==1）{
> > 
> > 
> > 仓库根目录："许可证"
> > 不多说了哈哈
> 
> 代码全挤main函数好像是可读性的问题，while（1==1）好像跟while（true）没啥区别

乐，能看出来代码的答辩程度lol

**Comment by zhiziqixingdeng** [comment]
> > > https://githubfast.com/zhiziqixingdeng/zhizi/blob/main/cpp%E6%96%87%E4%BB%B6/NOLstd%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F.cpp 6 代码全挤主函数
> > > > 而（1==1）{
> > > 
> > > 
> > > 仓库根目录：“许可证” 不多说了哈哈
> > 
> > 
> > 代码全挤main函数好像是可读性的问题，while（1==1）好像跟while（true）没啥区别
> 
> 乐，能看出来代码的答辩程度lol

的确，我确实该矫正一下SLtyz的代码习惯了

**Comment by SnowUnderwater** [comment]
加油吧…

**Comment by zhiziqixingdeng** [comment]
> 加油吧...

经过我的不断调教，SLtyz还是认为能跑就可以，我也想说6

**Comment by zhiziqixingdeng** [comment]
> > 加油吧...
> 
> 经过我的不断调教，SLtyz还是认为能跑就可以，我也想说6

到最后我只能放弃了（悲）
